source 'https://rubygems.org'


gem 'yell', '~>2.0'

gem 'rack' #for sidekiq
gem 'traject', '~>3.0'
gem 'match_map', '~>3.0'
gem 'sequel', '~>5.0'
gem 'httpclient', '~>2.0'
gem 'library_stdnums', '~>1.0'
gem 'sidekiq'

platforms :jruby do
  gem 'naconormalizer'
  gem 'jdbc-mysql', '~>8.0'
  gem 'psych'
  gem "traject-marc4j_reader", "~> 1.0"
  gem 'pry-debugger-jruby'
end

platforms :mri do
  gem 'mysql2'
  gem 'byebug'
end


gem 'marc-fastxmlwriter', '~>1.0'

gem 'high_level_browse', '>=1.1'

gem 'pry'


