source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem "hathifiles_database",
  git: "https://github.com/hathitrust/hathifiles_database",
  branch: "main"

gem "byebug"
