article: "Article"
newspaper_article: "Newspaper Article"
review: "Review"
book_chapter: "Book Chapter"
dissertation: "Dissertation"
patent: "Patent"
journal: "Journal"
reference_entry: "Reference Entry"
web_resource: "Web Resource"
book: "Book"
government_document: "Government Document"
conference_proceeding: "Conference Proceeding"
text_resource: "Text Resource"
image: "Image"
audio: "Audio"
video: "Video"
archival_material_manuscript: "Archival Material Manuscript"
dataset: "Dataset"
report: "Report"
standard: "Standard"
magazinearticle: "Magazine Article"
newsletterarticle: "Newsletter Article"
articles: "Articles"
newspaper_articles: "Newspaper Articles"
reviews: "Reviews"
book_chapters: "Book Chapters"
dissertations: "Dissertations"
patents: "Patents"
journals: "Journals"
reference_entrys: "Reference Entries"
web_resources: "Web Resources"
books: "Books"
government_documents: "Government Documents"
conference_proceedings: "Conference Proceedings"
text_resources: "Text Resources"
images: "Images"
audios: "Audios"
videos: "Videos"
archival_material_manuscripts: "Archival Material Manuscripts"
datasets: "Datasets"
reports: "Reports"
standards: "Standards"
magazinearticles: "Magazine Articles"
newsletterarticles: "Newsletter Articles"
