name: Run Tests

on: push

jobs:
  # Run tests
  test-ruby:
    runs-on: ubuntu-latest
    env:  
      BUNDLE_GEMFILE: ${{ github.workspace }}/umich_catalog_indexing/Gemfile
    steps:
      - uses: actions/checkout@v3
      - name: Set up ruby 3.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true
      - name: Create .env file
        working-directory: ./umich_catalog_indexing
        run: cat env.* > .env
      - name: Load .env file
        uses: xom9ikk/dotenv@v2.3.0
        with:
          path: umich_catalog_indexing
      - name: copy libLocInfo.yaml
        run: |
          cp .github/fixtures/libLocInfo.yaml umich_catalog_indexing/lib/translation_maps/umich/libLocInfo.yaml
          cp .github/fixtures/electronic_collections.yaml umich_catalog_indexing/lib/translation_maps/umich/electronic_collections.yaml
      - name: Run tests
        working-directory: ./umich_catalog_indexing
        run: bundle exec rspec

  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Create .env file
        working-directory: ./api
        run: cat env.* > .env
      - name: Load .env file
        uses: xom9ikk/dotenv@v2.3.0
        with:
          path: api
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python 3.11
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          cache: 'poetry'
      - name: install poetry packages    
        working-directory: ./api
        run: poetry install --no-root
      - name: Linting
        working-directory: ./api
        run: poetry run ruff check
      - name: Run tests
        env:
          CI: "true"
        working-directory: ./api
        run: poetry run pytest 
